server:
  port: 8080
#jsp
spring:
#  mvc:
 #   view:
  #    prefix: /WEB-INF/shop/
   #   suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 1234
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-1.cm6o8dl5mzni.ap-northeast-2.rds.amazonaws.com:3306/mysqlname
#    username: admin
#    password: qlxm4wh!!
#    
#  jpa:
#    hibernate:
#      ddl-auto: update

mybatis:
  type-aliases-package: data.mapper,data.dto
  mapper-locations:
  - /mapper/**/*.xml